language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install requests
  - pip install coveralls
script:
  coverage run --branch --source=catchments/ setup.py test
after_success:
  coveralls
